# Generated by Django 3.1.7 on 2021-03-29 22:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import quicksell_app.models.basemodel
import quicksell_app.models.listing
import quicksell_app.models.user
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', quicksell_app.models.user.LowercaseEmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('balance', models.IntegerField(default=0)),
                ('password_reset_code', models.IntegerField(blank=True, null=True)),
                ('password_reset_request_time', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', quicksell_app.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quicksell_app.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_chats', to=settings.AUTH_USER_MODEL)),
                ('interlocutor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='participated_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', quicksell_app.models.basemodel.QuicksellManager()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Sold'), (3, 'Closed'), (4, 'Deleted')], default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('date_expires', models.DateTimeField(default=quicksell_app.models.listing.default_expiration_date)),
                ('condition_new', models.BooleanField(default=False)),
                ('characteristics', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=models.SET(quicksell_app.models.listing.uncategorized), to='quicksell_app.category')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', quicksell_app.models.basemodel.QuicksellManager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', quicksell_app.models.basemodel.QuicksellManager()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/listings/')),
                ('order', models.SmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='quicksell_app.listing')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', quicksell_app.models.basemodel.QuicksellManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='quicksell_app.chat')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', quicksell_app.models.basemodel.QuicksellManager()),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quicksell_app.location'),
        ),
        migrations.AddField(
            model_name='chat',
            name='listing',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='quicksell_app.listing'),
        ),
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', quicksell_app.models.basemodel.QuicksellManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='_profile', serialize=False, to='quicksell_app.user')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateField(default=datetime.date.today, editable=False)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField(blank=True)),
                ('online', models.BooleanField(default=True)),
                ('rating', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/avatars')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quicksell_app.location')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', quicksell_app.models.basemodel.QuicksellManager()),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='quicksell_app.profile'),
        ),
    ]
